# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - name: Checking out code
      uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install package and dependencies
      run: |
        python setup.py develop
    - name: Dependencies needed for coverage and unit tests
      run: |
        conda install matplotlib
        pip install tqdm
        pip install dill
        pip install tensorboardX cox requests
        pip install advertorch copt
        pip install git+https://github.com/RobustBench/robustbench
        pip install coveralls coverage pytest-cov
    - name: Dependencies needed for sphinx
      run: |
        pip install sphinx sphinx-gallery
        pip install memory_profiler
    - name: Running unit tests
      run: |
        py.test -v --cov=chop
